### ISSUE TITLE
Blueprint: Offer default option

### ISSUE THREAD

**Issue by oliverwendenburg** [dweidner/kirby-firewall#7]
Sometimes it would be nice to have a default option, say: All articles should be in "draft mode" only visible to logged in users when created.

In my case (school), I could then forbid to update the article (via Kirby permissions), if the user has a specific role. For a better workflow a default value for the field would be perfect.

**Comment by dweidner** [comment]
You can specify default values within your blueprint:

```yml
# site/blueprint/article.yml

title: Article
pages: false
files: true
fields:
  firewall:
    label: Firewall
    type: firewall
    default:
      roles:
        - admin
      users:
       - dweidner
# …
```

Is that what you are looking for?
